import Foundation

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    
    @Published var currentLanguage: Language = .english
    
    private var translations: [String: [String: String]] = [
        "en": [
            "perfect_brew": "Perfect Brew",
            "brewing_guide": "Brewing Guide",
            "time_remaining": "Time Remaining",
            "time_elapsed": "Time Elapsed",
            "bloom_remaining": "Bloom Remaining",
            "step_remaining": "Step Remaining",
            "current_step": "Current Step",
            "preparation_step": "Preparation Step",
            "preparation_progress": "Preparation Progress",
            "seconds": "seconds",
            "steps": "steps",
            "next_step": "Next Step",
            "reset": "Reset",
            "start_brewing": "Start Brewing",
            "pause": "Pause",
            "resume": "Resume",
            "finish_brewing": "Finish Brewing",
            "settings": "Settings",
            "units": "Units",
            "temperature": "Temperature",
            "weight": "Weight",
            "celsius": "Celsius",
            "fahrenheit": "Fahrenheit",
            "grams": "Grams",
            "ounces": "Ounces",
            "language": "Language",
            "english": "English",
            "brewing_assistance": "Brewing Assistance",
            "haptic_feedback": "Haptic Feedback",
            "voice_cues": "Voice Cues",
            "about": "About",
            "version": "Version",
            "build": "Build",
            "rate_your_brew": "Rate Your Brew",
            "how_was_your_brew": "How was your brew?",
            "notes_optional": "Notes (Optional)",
            "submit_feedback": "Submit Feedback",
            "thank_you": "Thank You!",
            "feedback_submitted": "Your feedback has been submitted.",
            "ok": "OK",
            "poor": "Poor",
            "fair": "Fair",
            "good": "Good",
            "very_good": "Very Good",
            "excellent": "Excellent",
            "feedback": "Feedback",
            "brew_execution": "Brew Execution",
            "followed_recipe_label": "Did you follow the recipe exactly?",
            "brew_time_match_label": "Did the total brew time match the recipe?",
            "flow_rate_label": "How was the flow rate during the pour?",
            "taste_profile": "Taste Profile",
            "sweetness_level": "Sweetness Level",
            "bitterness_level": "Bitterness Level",
            "acidity_level": "Acidity Level",
            "body_mouthfeel": "Body/Mouthfeel",
            "flavor_notes": "Flavor Notes (Optional)",
            "adjustment_suggestions": "Adjustment Suggestions",
            "adjust_next_time_label": "Would you change anything next time?",
            "adjustment_areas_label": "If yes, what would you adjust?",
            "additional_notes": "Additional Notes (Optional)",
            "yes": "Yes",
            "mostly": "Mostly",
            "no": "No",
            "on_time": "On time",
            "bit_short": "A bit short",
            "too_long": "Too long",
            "too_fast": "Too fast",
            "just_right": "Just right",
            "too_slow": "Too slow",
            "light": "Light",
            "medium": "Medium",
            "full": "Full",
            "fruity": "Fruity",
            "chocolaty": "Chocolaty",
            "nutty": "Nutty",
            "earthy": "Earthy",
            "floral": "Floral",
            "spicy": "Spicy",
            "herbal": "Herbal",
            "grind_size": "Grind size",
            "ratio": "Ratio",
            "brew_time": "Brew time",
            "pour_technique": "Pour technique"
        ],
        "es": [
            "perfect_brew": "Café Perfecto",
            "brewing_guide": "Guía de Preparación",
            "time_remaining": "Tiempo Restante",
            "time_elapsed": "Tiempo Transcurrido",
            "bloom_remaining": "Bloom Restante",
            "step_remaining": "Paso Restante",
            "current_step": "Paso Actual",
            "preparation_step": "Paso de Preparación",
            "preparation_progress": "Progreso de Preparación",
            "seconds": "segundos",
            "steps": "pasos",
            "next_step": "Siguiente Paso",
            "reset": "Reiniciar",
            "start_brewing": "Comenzar Preparación",
            "pause": "Pausar",
            "resume": "Reanudar",
            "finish_brewing": "Terminar Preparación",
            "settings": "Configuración",
            "units": "Unidades",
            "temperature": "Temperatura",
            "weight": "Peso",
            "celsius": "Celsius",
            "fahrenheit": "Fahrenheit",
            "grams": "Gramos",
            "ounces": "Onzas",
            "language": "Idioma",
            "english": "Inglés",
            "brewing_assistance": "Asistencia de Preparación",
            "haptic_feedback": "Retroalimentación Háptica",
            "voice_cues": "Indicaciones de Voz",
            "about": "Acerca de",
            "version": "Versión",
            "build": "Compilación",
            "rate_your_brew": "Califica tu Café",
            "how_was_your_brew": "¿Cómo estuvo tu café?",
            "notes_optional": "Notas (Opcional)",
            "submit_feedback": "Enviar Comentarios",
            "thank_you": "¡Gracias!",
            "feedback_submitted": "Tus comentarios han sido enviados.",
            "ok": "OK",
            "poor": "Malo",
            "fair": "Regular",
            "good": "Bueno",
            "very_good": "Muy Bueno",
            "excellent": "Excelente",
            "feedback": "Comentarios",
            "brew_execution": "Ejecución de la Preparación",
            "followed_recipe_label": "¿Seguiste la receta exactamente?",
            "brew_time_match_label": "¿El tiempo total de preparación coincidió con la receta?",
            "flow_rate_label": "¿Cómo fue el flujo durante el vertido?",
            "taste_profile": "Perfil de Sabor",
            "sweetness_level": "Nivel de Dulzura",
            "bitterness_level": "Nivel de Amargura",
            "acidity_level": "Nivel de Acidez",
            "body_mouthfeel": "Cuerpo/Sensación en Boca",
            "flavor_notes": "Notas de Sabor (Opcional)",
            "adjustment_suggestions": "Sugerencias de Ajuste",
            "adjust_next_time_label": "¿Cambiarías algo la próxima vez?",
            "adjustment_areas_label": "Si es sí, ¿qué ajustarías?",
            "additional_notes": "Notas Adicionales (Opcional)",
            "yes": "Sí",
            "mostly": "Mayormente",
            "no": "No",
            "on_time": "A tiempo",
            "bit_short": "Un poco corto",
            "too_long": "Demasiado largo",
            "too_fast": "Demasiado rápido",
            "just_right": "Perfecto",
            "too_slow": "Demasiado lento",
            "light": "Ligero",
            "medium": "Medio",
            "full": "Completo",
            "fruity": "Frutal",
            "chocolaty": "Chocolateado",
            "nutty": "Nuez",
            "earthy": "Terroso",
            "floral": "Floral",
            "spicy": "Picante",
            "herbal": "Herbáceo",
            "grind_size": "Tamaño de molido",
            "ratio": "Proporción",
            "brew_time": "Tiempo de preparación",
            "pour_technique": "Técnica de vertido"
        ]
    ]
    
    private init() {}
    
    func updateLanguage(_ language: Language) {
        currentLanguage = language
    }
    
    func localizedString(_ key: String) -> String {
        let languageCode = currentLanguage.rawValue
        return translations[languageCode]?[key] ?? translations["en"]?[key] ?? key
    }
}

// Extension to make localization easier to use
extension String {
    var localized: String {
        return LocalizationManager.shared.localizedString(self)
    }
} 