import Foundation

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    
    @Published var currentLanguage: Language = .english
    
    private var translations: [String: [String: String]] = [
        "en": [
            "perfect_brew": "Perfect Brew",
            "brewing_guide": "Brewing Guide",
            "time_remaining": "Time Remaining",
            "time_elapsed": "Time Elapsed",
            "elapsed": "elapsed",
            "remaining": "remaining",
            "bloom_remaining": "Bloom Remaining",
            "step_remaining": "Step Remaining",
            "current_step": "Current Step",
            "preparation_step": "Preparation Step",
            "preparation_progress": "Preparation Progress",
            "seconds": "seconds",
            "steps": "steps",
            "next_step": "Next Step",
            "reset": "Reset",
            "start_brewing": "Start Brewing",
            "pause": "Pause",
            "resume": "Resume",
            "finish_brewing": "Finish Brewing",
            "settings": "Settings",
            "units": "Units",
            "temperature": "Temperature",
            "weight": "Weight",
            "celsius": "Celsius",
            "fahrenheit": "Fahrenheit",
            "grams": "Grams",
            "ounces": "Ounces",
            "language": "Language",
            "english": "English",
            "brewing_assistance": "Brewing Assistance",
            "haptic_feedback": "Haptic Feedback",
            "voice_cues": "Voice Cues",
            "about": "About",
            "version": "Version",
            "build": "Build",
            "rate_your_brew": "Rate Your Brew",
            "how_was_your_brew": "How was your brew?",
            "notes_optional": "Notes (Optional)",
            "submit_feedback": "Submit Feedback",
            "thank_you": "Thank You!",
            "feedback_submitted": "Your feedback has been submitted.",
            "ok": "OK",
            "poor": "Poor",
            "fair": "Fair",
            "good": "Good",
            "very_good": "Very Good",
            "excellent": "Excellent",
            "feedback": "Feedback",
            "brew_execution": "Brew Execution",
            "followed_recipe_label": "Did you follow the recipe exactly?",
            "brew_time_match_label": "Did the total brew time match the recipe?",
            "flow_rate_label": "How was the flow rate during the pour?",
            "taste_profile": "Taste Profile",
            "expected_profile": "Expected Profile",
            "expected_flavor_notes": "Expected Flavor Notes",
            "you_should_taste": "According to this coffee, you should taste...",
            "flavor_notes_experienced": "Flavor Notes You Experienced",
            "did_you_taste": "Did you taste",
            "did_you_taste_note": "Mark the flavor notes you experienced:",
            "not_sure": "Not sure",
            "sweetness_level": "Sweetness",
            "bitterness_level": "Bitterness",
            "acidity_level": "Acidity",
            "compared_to_wanted_prefix": "Compared to what you wanted, the ",
            "compared_to_wanted_suffix": " was...",
            "not_enough": "Not enough",
            "perfect": "Perfect",
            "too_much": "Too much",
            "body_mouthfeel": "Body/Mouthfeel",
            "flavor_notes": "Flavor Notes (Optional)",
            "adjustment_suggestions": "Adjustment Suggestions",
            "adjust_next_time_label": "Would you change anything next time?",
            "adjustment_areas_label": "If yes, what would you adjust?",
            "additional_notes": "Additional Notes (Optional)",
            "yes": "Yes",
            "mostly": "Mostly",
            "no": "No",
            "on_time": "On time",
            "bit_short": "A bit short",
            "too_long": "Too long",
            "too_fast": "Too fast",
            "just_right": "Just right",
            "too_slow": "Too slow",
            "light": "Light",
            "medium": "Medium",
            "full": "Full",
            "fruity": "Fruity",
            "chocolaty": "Chocolaty",
            "nutty": "Nutty",
            "earthy": "Earthy",
            "floral": "Floral",
            "spicy": "Spicy",
            "herbal": "Herbal",
            "grind_size": "Grind size",
            "ratio": "Ratio",
            "brew_time": "Brew time",
            "pour_technique": "Pour technique",
            "overall_rating": "Overall Rating",
            "spanish": "Spanish",
            "notes": "Notes",
            "listen": "Listen",
            "brew_parameters": "Brew Parameters",
            "coffee": "Coffee",
            "water": "Water",
            "total_time": "Total Time",
            "grinder_settings": "Grinder Settings",
            "preparation_steps": "Preparation Steps",
            "brewing_steps": "Brewing Steps",
            "no_recipes_found": "No recipes found",
            "difficulty": "Difficulty",
            "all_difficulties": "All Difficulties",
            "beginner": "Beginner",
            "intermediate": "Intermediate",
            "advanced": "Advanced",
            "dose_filter": "Dose Filter",
            "all_doses": "All Doses",
            "match_my_coffee": "Match My Coffee",
            "recommendations": "Recommendations",
            "add_coffee": "Add Coffee",
            "select_coffee": "Select Coffee",
            "coffee_name": "Coffee Name",
            "roaster": "Roaster",
            "roast_level": "Roast Level",
            "process": "Process",
            "flavor_tags": "Flavor Tags",
            "country": "Country",
            "region": "Region",
            "variety": "Variety",
            "altitude": "Altitude",
            "roast_date": "Roast Date",
            "save": "Save",
            "cancel": "Cancel",
            "edit": "Edit",
            "delete": "Delete",
            "history": "History",
            "home": "Home",
            "enjoy_your_coffee": "Enjoy your coffee!",
            "back": "Back",
            "recipe_details": "Recipe Details",
            "select_coffee_for_logs": "Select Coffee (for logs)",
            "craft_perfect_cup": "Craft the perfect cup",
            "find_perfect_recipe": "Find the perfect recipe for your beans",
            "preference_questionnaire_title": "Your Preferences",
            "body_preference_question": "What body do you prefer?",
            "body_texture_question": "Do you prefer tea-like or creamy/syrupy texture?",
            "acidity_preference_question": "What acidity level do you enjoy?",
            "acidity_hint": "Fruity coffees are usually higher in acidity, chocolatey/nutty are usually lower",
            "sweetness_preference_question": "Sweetness or Bitterness preference?",
            "recommendation_type_question": "Recommendation type?",
            "recommendation_type_general": "General",
            "recommendation_type_method_specific": "Method-specific",
            "body_texture_tea_like": "Tea-like",
            "body_texture_creamy_syrupy": "Creamy/Syrupy",
            "acidity_bright_juicy": "Bright/Juicy",
            "acidity_smooth_low": "Smooth/Low",
            "sweetness_sweet": "Sweet",
            "sweetness_balanced": "Balanced",
            "sweetness_bitter": "Bitter",
            "get_recommendations_button": "Get Recommendations",
            "skip_preferences_button": "Skip",
            "matches_preference_body": "Matches your preference for",
            "method_highlights_clarity": "Method highlights brightness",
            "method_highlights_body": "Method emphasizes body",
            "brew_log": "Brew Log",
            "brew_details": "Brew Details",
            "view_brew_recommendations": "View Brew Recommendations",
            "brew_method": "Brew Method",
            "start_new_brew": "Start New Brew",
            "brew_history": "Brew History",
            "search_recipes": "Search recipes...",
            "all": "All",
            "amount_of_coffee": "Amount of Coffee (grams)",
            "expert": "Expert",
            "log": "Log",
            "v60_recipes": "V60 Recipes",
            "aeropress_recipes": "AeroPress Recipes",
            "french_press_recipes": "French Press Recipes",
            "chemex_recipes": "Chemex Recipes",
            "clicks": "clicks",
            "recipes": "Recipes",
            "equipment_needed": "Equipment Needed",
            "next_at": "Next at",
            "grinder_brand": "Grinder Brand",
            "last_time_brewed": "Last time you brewed this:",
            "ready_to_start_brewing": "Ready to start brewing!",
            "brewing_in_progress": "Brewing...",
            "try_adjusting_filters": "Try adjusting your search or filters",
            "recipe_overview": "Recipe Overview",
            "review_before_brewing": "Review before brewing",
            "start_step_by_step_guide": "Start Step-by-Step Brewing Guide",
            "follow_guided_steps": "Follow guided steps with timer",
            "brewing_steps_preview": "Brewing Steps Preview",
            "view_all_steps": "View All Steps",
            "collapse_steps": "Collapse Steps",
            "step": "step",
            "total": "total"
        ],
        "es": [
            "perfect_brew": "Café Perfecto",
            "brewing_guide": "Guía de Preparación",
            "time_remaining": "Tiempo Restante",
            "time_elapsed": "Tiempo Transcurrido",
            "elapsed": "transcurrido",
            "remaining": "restante",
            "bloom_remaining": "Bloom Restante",
            "step_remaining": "Paso Restante",
            "current_step": "Paso Actual",
            "preparation_step": "Paso de Preparación",
            "preparation_progress": "Progreso de Preparación",
            "seconds": "segundos",
            "steps": "pasos",
            "next_step": "Siguiente Paso",
            "reset": "Reiniciar",
            "start_brewing": "Comenzar Preparación",
            "pause": "Pausar",
            "resume": "Reanudar",
            "finish_brewing": "Terminar Preparación",
            "settings": "Configuración",
            "units": "Unidades",
            "temperature": "Temperatura",
            "weight": "Peso",
            "celsius": "Celsius",
            "fahrenheit": "Fahrenheit",
            "grams": "Gramos",
            "ounces": "Onzas",
            "language": "Idioma",
            "english": "Inglés",
            "brewing_assistance": "Asistencia de Preparación",
            "haptic_feedback": "Retroalimentación Háptica",
            "voice_cues": "Indicaciones de Voz",
            "about": "Acerca de",
            "version": "Versión",
            "build": "Compilación",
            "rate_your_brew": "Califica tu Café",
            "how_was_your_brew": "¿Cómo estuvo tu café?",
            "notes_optional": "Notas (Opcional)",
            "submit_feedback": "Enviar Comentarios",
            "thank_you": "¡Gracias!",
            "feedback_submitted": "Tus comentarios han sido enviados.",
            "ok": "OK",
            "poor": "Malo",
            "fair": "Regular",
            "good": "Bueno",
            "very_good": "Muy Bueno",
            "excellent": "Excelente",
            "feedback": "Comentarios",
            "brew_execution": "Ejecución de la Preparación",
            "followed_recipe_label": "¿Seguiste la receta exactamente?",
            "brew_time_match_label": "¿El tiempo total de preparación coincidió con la receta?",
            "flow_rate_label": "¿Cómo fue el flujo durante el vertido?",
            "taste_profile": "Perfil de Sabor",
            "expected_profile": "Perfil Esperado",
            "expected_flavor_notes": "Notas de Sabor Esperadas",
            "you_should_taste": "Según este café, deberías sentir...",
            "flavor_notes_experienced": "Notas que Sentiste",
            "did_you_taste": "¿Sentiste notas de",
            "did_you_taste_note": "Marca las notas de sabor que experimentaste:",
            "not_sure": "No estoy seguro",
            "sweetness_level": "Dulzura",
            "bitterness_level": "Amargura",
            "acidity_level": "Acidez",
            "compared_to_wanted_prefix": "Comparado con lo que querías, la ",
            "compared_to_wanted_suffix": " fue...",
            "not_enough": "Insuficiente",
            "perfect": "Perfecto",
            "too_much": "Demasiado",
            "body_mouthfeel": "Cuerpo/Sensación en Boca",
            "flavor_notes": "Notas de Sabor (Opcional)",
            "adjustment_suggestions": "Sugerencias de Ajuste",
            "adjust_next_time_label": "¿Cambiarías algo la próxima vez?",
            "adjustment_areas_label": "Si es sí, ¿qué ajustarías?",
            "additional_notes": "Notas Adicionales (Opcional)",
            "yes": "Sí",
            "mostly": "Mayormente",
            "no": "No",
            "on_time": "A tiempo",
            "bit_short": "Un poco corto",
            "too_long": "Demasiado largo",
            "too_fast": "Demasiado rápido",
            "just_right": "Perfecto",
            "too_slow": "Demasiado lento",
            "light": "Ligero",
            "medium": "Medio",
            "full": "Completo",
            "fruity": "Frutal",
            "chocolaty": "Chocolateado",
            "nutty": "Nuez",
            "earthy": "Terroso",
            "floral": "Floral",
            "spicy": "Picante",
            "herbal": "Herbáceo",
            "grind_size": "Tamaño de molido",
            "ratio": "Proporción",
            "brew_time": "Tiempo de preparación",
            "pour_technique": "Técnica de vertido",
            "overall_rating": "Calificación General",
            "spanish": "Español",
            "notes": "Notas",
            "listen": "Escuchar",
            "brew_parameters": "Parámetros de Preparación",
            "coffee": "Café",
            "water": "Agua",
            "total_time": "Tiempo Total",
            "grinder_settings": "Configuración del Molino",
            "preparation_steps": "Pasos de Preparación",
            "brewing_steps": "Pasos de Preparación",
            "no_recipes_found": "No se encontraron recetas",
            "difficulty": "Dificultad",
            "all_difficulties": "Todas las Dificultades",
            "beginner": "Principiante",
            "intermediate": "Intermedio",
            "advanced": "Avanzado",
            "dose_filter": "Filtro de Dosis",
            "all_doses": "Todas las Dosis",
            "match_my_coffee": "Combinar Mi Café",
            "recommendations": "Recomendaciones",
            "add_coffee": "Agregar Café",
            "select_coffee": "Seleccionar Café",
            "coffee_name": "Nombre del Café",
            "roaster": "Tostador",
            "roast_level": "Nivel de Tueste",
            "process": "Proceso",
            "flavor_tags": "Etiquetas de Sabor",
            "country": "País",
            "region": "Región",
            "variety": "Variedad",
            "altitude": "Altitud",
            "roast_date": "Fecha de Tueste",
            "save": "Guardar",
            "cancel": "Cancelar",
            "edit": "Editar",
            "delete": "Eliminar",
            "history": "Historial",
            "home": "Inicio",
            "enjoy_your_coffee": "¡Disfruta tu café!",
            "back": "Atrás",
            "recipe_details": "Detalles de Receta",
            "select_coffee_for_logs": "Seleccionar Café (para registro)",
            "craft_perfect_cup": "Prepara el café perfecto",
            "find_perfect_recipe": "Encuentra la receta perfecta para tus granos",
            "preference_questionnaire_title": "Tus Preferencias",
            "body_preference_question": "¿Qué cuerpo prefieres?",
            "body_texture_question": "¿Prefieres textura tipo té o cremosa/sirope?",
            "acidity_preference_question": "¿Qué nivel de acidez disfrutas?",
            "acidity_hint": "Los cafés frutales suelen tener mayor acidez, los chocolatosos/nuez suelen tener menor",
            "sweetness_preference_question": "¿Preferencia de dulzor o amargor?",
            "recommendation_type_question": "¿Tipo de recomendación?",
            "recommendation_type_general": "General",
            "recommendation_type_method_specific": "Por método específico",
            "body_texture_tea_like": "Tipo té",
            "body_texture_creamy_syrupy": "Cremosa/Sirope",
            "acidity_bright_juicy": "Brillante/Jugosa",
            "acidity_smooth_low": "Suave/Baja",
            "sweetness_sweet": "Dulce",
            "sweetness_balanced": "Equilibrado",
            "sweetness_bitter": "Amargo",
            "get_recommendations_button": "Obtener Recomendaciones",
            "skip_preferences_button": "Omitir",
            "matches_preference_body": "Coincide con tu preferencia de",
            "method_highlights_clarity": "El método resalta la brillantez",
            "method_highlights_body": "El método enfatiza el cuerpo",
            "brew_log": "Registro de Preparaciones",
            "brew_details": "Detalles de la Preparación",
            "view_brew_recommendations": "Ver Recomendaciones de Preparación",
            "brew_method": "Método de Preparación",
            "start_new_brew": "Nueva Preparación",
            "brew_history": "Historial de Preparaciones",
            "search_recipes": "Buscar recetas...",
            "all": "Todos",
            "amount_of_coffee": "Cantidad de Café (gramos)",
            "expert": "Experto",
            "log": "Registro",
            "v60_recipes": "Recetas V60",
            "aeropress_recipes": "Recetas AeroPress",
            "french_press_recipes": "Recetas Prensa Francesa",
            "chemex_recipes": "Recetas Chemex",
            "clicks": "clics",
            "recipes": "Recetas",
            "equipment_needed": "Equipo Necesario",
            "next_at": "Siguiente a las",
            "grinder_brand": "Marca de Molino",
            "last_time_brewed": "La última vez que preparaste esto:",
            "ready_to_start_brewing": "¡Listo para preparar!",
            "brewing_in_progress": "Preparando...",
            "try_adjusting_filters": "Intenta ajustar tu búsqueda o filtros",
            "recipe_overview": "Resumen de Receta",
            "review_before_brewing": "Revisa antes de preparar",
            "start_step_by_step_guide": "Iniciar Guía Paso a Paso",
            "follow_guided_steps": "Sigue pasos guiados con temporizador",
            "brewing_steps_preview": "Vista Previa de Pasos",
            "view_all_steps": "Ver Todos los Pasos",
            "collapse_steps": "Colapsar Pasos",
            "step": "paso",
            "total": "total"
        ]
    ]
    
    private init() {}
    
    func updateLanguage(_ language: Language) {
        currentLanguage = language
    }
    
    func localizedString(_ key: String) -> String {
        let languageCode = currentLanguage.rawValue
        return translations[languageCode]?[key] ?? translations["en"]?[key] ?? key
    }
}

// Extension to make localization easier to use
extension String {
    var localized: String {
        return LocalizationManager.shared.localizedString(self)
    }
} 